[parity]
chain = "dev"
# Syncing is disabled (no network)

[account]
unlock = []
password = ["/parity/password.txt"]

[rpc]
hosts = ["all"]
interface = "all"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "parity_accounts", "personal"]

[websockets]
hosts = ["all"]
interface = "all"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "parity_accounts", "personal"]

[misc]
log_file = "/parity/parity.log"

